/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'nwillc' at '8/7/16 3:59 PM' with Gradle 2.9
 *
 * @author nwillc, @date 8/7/16 3:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
